apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c05i7mmvr-go
  janus-idp.io/tekton: c05i7mmvr-go
  backstage.io/kubernetes-id: c05i7mmvr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c05i7mmvr-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
